### ISSUE TITLE
master branch is missing.

### ISSUE THREAD

**Issue by EricLScace** [squad-three/squad-three-front-end#1]

**Comment by lisawilliams** [comment]
OK, our setup lab accidentally had everyone creating development as the master branch. 

I created a master branch, pushed it and changed the settings of the repo so that "master" is the default branch.

**Comment by lisawilliams** [comment]
Let me know if you can get to a state where you have both branches and master is your default branch and then I will close the issue.

**Comment by EricLScace** [comment]
I have both.
