### ISSUE TITLE
Table Border Top/Bottom Disappears with Pagination CSS fix

### ISSUE THREAD

**Issue by constaac** [squad-three/squad-three-front-end#108]

**Comment by lisawilliams** [comment]
<img width="1276" alt="screen shot 2017-07-06 at 4 08 24 pm" src="https://user-images.githubusercontent.com/809042/27930812-f8b90308-6265-11e7-83f2-961008709971.png">

**Comment by lisawilliams** [comment]
We're looking for table.dataTable thead, th, the border-bottom attribute, which is on jquery.dataTables.css, line 22 (see above screenshot). 

I'm going to create an override file for this since fixing pagination, for some unknown reason, gets rid of this.
