### ISSUE TITLE
requirement: README on front-end repo with essential contents

### ISSUE THREAD

**Issue by EricLScace** [squad-three/squad-three-front-end#11]
A short description of your application.
A brief explanation of the technologies (Node modules, Express middleware etc) used.
A couple of paragraphs detailing the general approach you took.
Notes on any unsolved problems or major hurdles your team had to overcome.
Installation instructions for any dependencies.
A link to your user stories – who are your users, what do they want, and why?
A link to your ERD - what data models does your app use?
A link to your wireframes – sketches of major views / interfaces in your application.
A link to the deployed front-end app.
A link to the repo for your back-end.

**Comment by lisawilliams** [comment]
[Draft README](https://github.com/squad-three/squad-three-front-end/blob/b3cb9b083d4912b44d47c48d44e9ce3099c94bf4/README.md)
