### ISSUE TITLE
Strange grey blob over C in cost in New/Edit fields

### ISSUE THREAD

**Issue by constaac** [squad-three/squad-three-front-end#90]

**Comment by EricLScace** [comment]
Can't reproduce.

**Comment by constaac** [comment]
![screen shot 2017-06-29 at 3 20 40 am](https://user-images.githubusercontent.com/6073071/27675957-177836c0-5c7a-11e7-861b-c565f93a4cf9.png)

**Comment by constaac** [comment]
For both add and edit

**Comment by EricLScace** [comment]
Addressed with issue #56
