### ISSUE TITLE
DataTables warning -- Ajax error on page load

### ISSUE THREAD

**Issue by lisawilliams** [squad-three/squad-three-front-end#97]
Received this error on page load https://cl.ly/1L3Q1a0Y351z

**Comment by constaac** [comment]
I think this may be a backend issue, auto-assigning row ids to account for curl scripts

**Comment by EricLScace** [comment]
Adding check in back end to verify a row ID is present on every row read from the database. If not, one will be added and written back to the database (as well as returned to the client). See back-end https://github.com/squad-three/squad-three-back-end/issues/52
